// Gate for the npm release channel.
//
// This repo ships through three channels, and two of them release by opposite
// mechanisms. The marketplace channel is self-driving: bump
// dist/plugins/<name>/plugin.json, merge, and plugin-release.yml derives the
// tag and the release with no manual artifact. The npm channel is
// changesets-driven and needs a hand-written .changeset/*.md — without one,
// changesets/action finds nothing to version, opens no PR, and publishes
// nothing. That is working as designed and silent by design.
//
// It went wrong exactly as you would predict. condux 2.12.0, 2.13.0 and 2.14.0
// each shipped bundled-skill changes to the marketplace; none carried a
// changeset; @jabworks/condux sat at 0.7.0 while OpenCode users missed the
// conflicting-library warning, the doctor's conflict detection, and the
// --uninstall modes. Six files, +524 lines behind.
//
// Nothing caught it because opencode-dist.test.mjs asserts the generated tree
// matches the generator — which it did, every time. That guard checks
// source -> build drift. This one checks build -> published drift, which is the
// half nobody owned.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..');
const PKG = 'packages/condux-opencode';
const PKG_NAME = '@jabworks/condux';

// Everything the published tarball actually carries, per package.json "files".
// index.js is hand-written; skills/ and agents/ are generated by
// scripts/build-opencode.mjs. A change to any of them changes what a user
// installs, which is the whole trigger for needing a release.
const SHIPPED = [`${PKG}/index.js`, `${PKG}/agents`, `${PKG}/skills`];

function git(...args) {
  return execFileSync('git', args, { cwd: REPO_ROOT, encoding: 'utf8' }).trim();
}

// The last release commit. CHANGELOG.md in this package is written by exactly
// one thing — changesets' version step — so the commit that last touched it is
// the last time this package was versioned. Anchoring on package.json instead
// would be wrong: that file changes for description and metadata edits too.
function lastReleaseCommit() {
  return git('log', '-1', '--format=%H', '--', `${PKG}/CHANGELOG.md`);
}

function pendingChangesetsFor(pkgName) {
  const dir = path.join(REPO_ROOT, '.changeset');
  if (!fs.existsSync(dir)) return [];

  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.md') && f.toLowerCase() !== 'readme.md')
    .filter((f) => fs.readFileSync(path.join(dir, f), 'utf8').includes(pkgName));
}

test('git history is deep enough to answer this question', () => {
  // A guard that vanishes with its tool is how the 2026-08-05 frontmatter break
  // shipped, so this fails rather than skips. If CI checks out shallow, the fix
  // is fetch-depth: 0 on the job, not deleting the assertion.
  const anchor = lastReleaseCommit();

  assert.notEqual(anchor, '', `no commit found for ${PKG}/CHANGELOG.md — shallow clone? set fetch-depth: 0`);
  assert.doesNotThrow(
    () => git('cat-file', '-e', `${anchor}^{commit}`),
    'the release anchor is not reachable in this clone — set fetch-depth: 0',
  );
});

test('bundled content that changed since the last npm release has a pending changeset', () => {
  const anchor = lastReleaseCommit();
  const changed = git('diff', '--name-only', `${anchor}..HEAD`, '--', ...SHIPPED)
    .split('\n')
    .filter(Boolean);

  if (changed.length === 0) return;

  const pending = pendingChangesetsFor(PKG_NAME);

  assert.ok(
    pending.length > 0,
    `${changed.length} file(s) in the published surface changed since the last ${PKG_NAME} release ` +
      `(${anchor.slice(0, 7)}) with no pending changeset, so no Version Packages PR will open and ` +
      `npm keeps serving the old bundle:\n  ${changed.join('\n  ')}\n\n` +
      'Run `pnpm changeset` and describe the change from the OpenCode user\'s point of view.',
  );
});

test('a pending changeset names a real bump type', () => {
  // A changeset with a malformed frontmatter block is accepted by the file
  // system and ignored by changesets, which fails the same silent way as having
  // none at all.
  for (const file of pendingChangesetsFor(PKG_NAME)) {
    const src = fs.readFileSync(path.join(REPO_ROOT, '.changeset', file), 'utf8');
    const match = src.match(/^---\n([\s\S]*?)\n---/);

    assert.ok(match, `${file}: no frontmatter block`);
    assert.match(
      match[1],
      new RegExp(`['"]?${PKG_NAME.replace('/', '\\/')}['"]?\\s*:\\s*(major|minor|patch)`),
      `${file}: does not give ${PKG_NAME} a major/minor/patch bump`,
    );
  }
});
